// <auto-generated />
using System;
using Comex133Api.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comex133Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comex133Api.Domain.Entities.AgenteCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AgentesCarga");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ControleNavio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeNavio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroViagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroViagem")
                        .IsUnique();

                    b.ToTable("ControleNavios");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ControleNavioTrajeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ControleNavioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("PortoOrigemId")
                        .HasColumnType("int");

                    b.Property<string>("TrajetoDescricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ControleNavioId");

                    b.HasIndex("PortoDestinoId");

                    b.HasIndex("PortoOrigemId");

                    b.ToTable("ControleNaviosTrajetos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CifReais")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CifUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("DespachanteId")
                        .HasColumnType("int");

                    b.Property<decimal>("FobReais")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FobUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FreteInternacionalUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<bool>("Imutavel")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ParametroUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalGeralManual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("PortoOrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SeguroUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SolicitacaoOrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TamContainer")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("TaxaUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TaxaUsdAgente")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoAnteriorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("DespachanteId");

                    b.HasIndex("ImportadorId");

                    b.HasIndex("PortoDestinoId");

                    b.HasIndex("PortoOrigemId");

                    b.HasIndex("SolicitacaoOrcamentoId");

                    b.HasIndex("Status");

                    b.HasIndex("VersaoAnteriorId");

                    b.ToTable("CustosDespachante");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachanteDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustoDespachanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EntraBaseIcms")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CustoDespachanteId");

                    b.ToTable("CustosDespachanteDespesas");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachanteLi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustoDespachanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CustoDespachanteId");

                    b.ToTable("CustosDespachanteLi");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Despachante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Crn")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Despachantes");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.DespesaCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("DespesasCatalogo");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.EmbarqueNavioVinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DesvinculadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmbarqueAduanaId")
                        .HasColumnType("int");

                    b.Property<int>("NavioId")
                        .HasColumnType("int");

                    b.Property<int?>("NavioTrajetoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroViagem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VinculadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmbarqueAduanaId");

                    b.HasIndex("NavioId");

                    b.HasIndex("NavioTrajetoId");

                    b.ToTable("EmbarqueNavioVinculos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Exportador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cidade")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exportadores");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cidade")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Importador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Importadores");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ListaPrecoLcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeChines")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecoUsdPorCbm")
                        .HasColumnType("decimal(15,4)");

                    b.Property<decimal>("PrecoUsdPorKg")
                        .HasColumnType("decimal(15,4)");

                    b.HasKey("Id");

                    b.ToTable("ListaPrecoLcl");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ModeloDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDespesa");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ModeloDespesaItem", b =>
                {
                    b.Property<int>("ModeloDespesaId")
                        .HasColumnType("int");

                    b.Property<int>("DespesaCatalogoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("ModeloDespesaId", "DespesaCatalogoId");

                    b.HasIndex("DespesaCatalogoId");

                    b.ToTable("ModelosDespesaItens");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Navio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Armador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoImo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeNavio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Navios");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NavioTrajeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("datetime2");

                    b.Property<int>("NavioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroViagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PortoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("PortoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.Property<int>("StatusPerna")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NavioId");

                    b.HasIndex("PortoDestinoId");

                    b.HasIndex("PortoOrigemId");

                    b.ToTable("NaviosTrajetos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Ncm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AliqCOFINS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AliqICMS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AliqII")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AliqIPI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AliqPIS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoNcm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoNcm")
                        .IsUnique();

                    b.ToTable("Ncms");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NcmVinculadoCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AliCofins")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIcms")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIi")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIpi")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliPis")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BaseCalculo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustoDespachanteId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NcmId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroNcm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustoDespachanteId");

                    b.HasIndex("NcmId");

                    b.ToTable("NcmsVinculadosCusto");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CifReais")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CifUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FobReais")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FobUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FreteInternacional")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Honorarios")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Imutavel")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SolicitacaoOrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TamContainer")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("TaxaUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalDespesas")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalExtras")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalGeral")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalImpostos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoAnteriorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("SolicitacaoOrcamentoId");

                    b.HasIndex("VersaoAnteriorId");

                    b.ToTable("OrcamentosVenda");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustoDespachanteId")
                        .HasColumnType("int");

                    b.Property<int>("OrcamentoVendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustoDespachanteId");

                    b.HasIndex("OrcamentoVendaId", "CustoDespachanteId")
                        .IsUnique();

                    b.ToTable("OrcamentosVendaCustos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrcamentoVendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoVendaId");

                    b.ToTable("OrcamentosVendaDespesas");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaDespesaExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrcamentoVendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoVendaId");

                    b.ToTable("OrcamentosVendaDespesasExtras");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("ParametrosSistema");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.PortoDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PortosDestino");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.PortoOrigem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PortosOrigem");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("PortoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("PortoOrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TamContainer")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("ImportadorId");

                    b.HasIndex("PortoDestinoId");

                    b.HasIndex("PortoOrigemId");

                    b.ToTable("SolicitacoesOrcamento");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamentoDespachante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("DespachanteId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitacaoOrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("DespachanteId");

                    b.HasIndex("SolicitacaoOrcamentoId", "DespachanteId")
                        .IsUnique();

                    b.ToTable("SolicitacoesOrcamentoDespachantes");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamentoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkDocumento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SolicitacaoOrcamentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoOrcamentoId");

                    b.ToTable("SolicitacoesOrcamentoDocumentos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.UsuarioVinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoVinculo", "EntidadeId")
                        .IsUnique();

                    b.ToTable("UsuarioVinculos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ValorImpostoCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AliCofins")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIcms")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIi")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliIpi")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("AliPis")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("NcmVinculadoCustoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalImpostos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorIcms")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorIi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("NcmVinculadoCustoId");

                    b.ToTable("ValoresImpostoCusto");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ControleNavioTrajeto", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.ControleNavio", "ControleNavio")
                        .WithMany("Trajetos")
                        .HasForeignKey("ControleNavioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoDestino", "PortoDestino")
                        .WithMany()
                        .HasForeignKey("PortoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoOrigem", "PortoOrigem")
                        .WithMany()
                        .HasForeignKey("PortoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ControleNavio");

                    b.Navigation("PortoDestino");

                    b.Navigation("PortoOrigem");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachante", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Despachante", "Despachante")
                        .WithMany()
                        .HasForeignKey("DespachanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.Importador", "Importador")
                        .WithMany()
                        .HasForeignKey("ImportadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.PortoDestino", "PortoDestino")
                        .WithMany()
                        .HasForeignKey("PortoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoOrigem", "PortoOrigem")
                        .WithMany()
                        .HasForeignKey("PortoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.SolicitacaoOrcamento", "SolicitacaoOrcamento")
                        .WithMany()
                        .HasForeignKey("SolicitacaoOrcamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.CustoDespachante", "VersaoAnterior")
                        .WithMany()
                        .HasForeignKey("VersaoAnteriorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Despachante");

                    b.Navigation("Importador");

                    b.Navigation("PortoDestino");

                    b.Navigation("PortoOrigem");

                    b.Navigation("SolicitacaoOrcamento");

                    b.Navigation("VersaoAnterior");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachanteDespesa", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.CustoDespachante", "CustoDespachante")
                        .WithMany("Despesas")
                        .HasForeignKey("CustoDespachanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustoDespachante");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachanteLi", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.CustoDespachante", "CustoDespachante")
                        .WithMany("Lis")
                        .HasForeignKey("CustoDespachanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustoDespachante");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.EmbarqueNavioVinculo", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.SolicitacaoOrcamento", "EmbarqueAduana")
                        .WithMany()
                        .HasForeignKey("EmbarqueAduanaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.Navio", "Navio")
                        .WithMany("Vinculos")
                        .HasForeignKey("NavioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.NavioTrajeto", "NavioTrajeto")
                        .WithMany("Vinculos")
                        .HasForeignKey("NavioTrajetoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmbarqueAduana");

                    b.Navigation("Navio");

                    b.Navigation("NavioTrajeto");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ModeloDespesaItem", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.DespesaCatalogo", "DespesaCatalogo")
                        .WithMany("ModeloDespesaItens")
                        .HasForeignKey("DespesaCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.ModeloDespesa", "ModeloDespesa")
                        .WithMany("Itens")
                        .HasForeignKey("ModeloDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DespesaCatalogo");

                    b.Navigation("ModeloDespesa");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NavioTrajeto", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Navio", "Navio")
                        .WithMany("Trajetos")
                        .HasForeignKey("NavioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoDestino", "PortoDestino")
                        .WithMany()
                        .HasForeignKey("PortoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoOrigem", "PortoOrigem")
                        .WithMany()
                        .HasForeignKey("PortoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Navio");

                    b.Navigation("PortoDestino");

                    b.Navigation("PortoOrigem");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NcmVinculadoCusto", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.CustoDespachante", "CustoDespachante")
                        .WithMany("Ncms")
                        .HasForeignKey("CustoDespachanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.Ncm", "Ncm")
                        .WithMany()
                        .HasForeignKey("NcmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustoDespachante");

                    b.Navigation("Ncm");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVenda", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.SolicitacaoOrcamento", "SolicitacaoOrcamento")
                        .WithMany()
                        .HasForeignKey("SolicitacaoOrcamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.OrcamentoVenda", "VersaoAnterior")
                        .WithMany()
                        .HasForeignKey("VersaoAnteriorId");

                    b.Navigation("Cliente");

                    b.Navigation("SolicitacaoOrcamento");

                    b.Navigation("VersaoAnterior");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaCusto", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.CustoDespachante", "CustoDespachante")
                        .WithMany()
                        .HasForeignKey("CustoDespachanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.OrcamentoVenda", "OrcamentoVenda")
                        .WithMany("Custos")
                        .HasForeignKey("OrcamentoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustoDespachante");

                    b.Navigation("OrcamentoVenda");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaDespesa", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.OrcamentoVenda", "OrcamentoVenda")
                        .WithMany("Despesas")
                        .HasForeignKey("OrcamentoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrcamentoVenda");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVendaDespesaExtra", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.OrcamentoVenda", "OrcamentoVenda")
                        .WithMany("Extras")
                        .HasForeignKey("OrcamentoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrcamentoVenda");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamento", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.Importador", "Importador")
                        .WithMany()
                        .HasForeignKey("ImportadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comex133Api.Domain.Entities.PortoDestino", "PortoDestino")
                        .WithMany()
                        .HasForeignKey("PortoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.PortoOrigem", "PortoOrigem")
                        .WithMany()
                        .HasForeignKey("PortoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Importador");

                    b.Navigation("PortoDestino");

                    b.Navigation("PortoOrigem");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamentoDespachante", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Despachante", "Despachante")
                        .WithMany()
                        .HasForeignKey("DespachanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.SolicitacaoOrcamento", "SolicitacaoOrcamento")
                        .WithMany("Despachantes")
                        .HasForeignKey("SolicitacaoOrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despachante");

                    b.Navigation("SolicitacaoOrcamento");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamentoDocumento", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.SolicitacaoOrcamento", "SolicitacaoOrcamento")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitacaoOrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoOrcamento");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.UsuarioRole", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Role", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comex133Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.UsuarioVinculo", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Vinculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ValorImpostoCusto", b =>
                {
                    b.HasOne("Comex133Api.Domain.Entities.NcmVinculadoCusto", "NcmVinculadoCusto")
                        .WithMany("ValoresImposto")
                        .HasForeignKey("NcmVinculadoCustoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NcmVinculadoCusto");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ControleNavio", b =>
                {
                    b.Navigation("Trajetos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.CustoDespachante", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Lis");

                    b.Navigation("Ncms");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.DespesaCatalogo", b =>
                {
                    b.Navigation("ModeloDespesaItens");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.ModeloDespesa", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Navio", b =>
                {
                    b.Navigation("Trajetos");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NavioTrajeto", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.NcmVinculadoCusto", b =>
                {
                    b.Navigation("ValoresImposto");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.OrcamentoVenda", b =>
                {
                    b.Navigation("Custos");

                    b.Navigation("Despesas");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.SolicitacaoOrcamento", b =>
                {
                    b.Navigation("Despachantes");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Comex133Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
